# GitHub Sponsors configuration for BabySounds

# Support BabySounds development
github: vpavlov-me

# Alternative funding options
patreon: babysounds
ko_fi: babysounds
buy_me_a_coffee: babysounds

# Custom funding URLs
custom: 
  - "https://apps.apple.com/app/babysounds/idXXXXXXXXX"
  - "https://www.babysounds.com/support" 