name: 🐛 Bug Report
description: Create a bug report for BabySounds iOS app
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🍼 BabySounds Bug Report
        
        Thank you for reporting a bug! Please fill out this form to help us fix the issue quickly.
        
        **⚠️ PRIVACY NOTICE**: Never include personal information about children or families in bug reports.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: This report contains no personal information about children
          required: true
        - label: I have tested on the latest version available
          required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Information
      description: What device are you using?
      options:
        - iPhone SE (3rd generation)
        - iPhone 14/14 Plus
        - iPhone 14 Pro/14 Pro Max
        - iPhone 15/15 Plus
        - iPhone 15 Pro/15 Pro Max
        - iPad (10th generation)
        - iPad Air (5th generation)
        - iPad Pro
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: ios_version
    attributes:
      label: iOS Version
      description: What iOS version are you running?
      options:
        - iOS 17.0
        - iOS 17.1
        - iOS 17.2
        - iOS 17.3
        - iOS 17.4
        - iOS 17.5
        - iOS 18.0 (Beta)
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: app_version
    attributes:
      label: App Version
      description: What version of BabySounds are you using?
      options:
        - v1.0.0 (App Store)
        - v1.1.0 (App Store)
        - v1.2.0 (TestFlight)
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - 🔴 Critical - App crashes or becomes unusable
        - 🟠 High - Major feature doesn't work
        - 🟡 Medium - Minor feature issue or unexpected behavior
        - 🟢 Low - Cosmetic or minor improvement
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Bug Category
      description: Which area does this bug affect?
      options:
        - 🎵 Audio playback/mixing
        - ⏰ Sleep schedules/notifications
        - 💳 In-app purchases/subscriptions
        - 🔒 Parental gate/safety features
        - ♿ Accessibility/VoiceOver
        - 🔋 Background playback/battery
        - 🎨 User interface/design
        - 📱 App navigation/performance
        - 🛡️ Privacy/security
        - Other (specify in description)
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe what actually happens, including any error messages...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Open the app
        2. Navigate to...
        3. Tap on...
        4. Bug occurs
    validations:
      required: true

  - type: textarea
    id: audio_context
    attributes:
      label: Audio Context (if applicable)
      description: If this is an audio-related bug, please provide details
      placeholder: |
        - Which sounds were playing?
        - How many tracks were active?
        - Was background audio enabled?
        - Any volume or hearing protection warnings?

  - type: textarea
    id: accessibility_context
    attributes:
      label: Accessibility Context (if applicable)
      description: If using accessibility features, please provide details
      placeholder: |
        - VoiceOver enabled?
        - Switch Control enabled?
        - Any other accessibility settings?
        - Specific accessibility issues encountered?

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that might help us fix this bug
      placeholder: |
        - Screenshots (if helpful)
        - Console logs (if you have them)
        - Network connectivity status
        - Any other relevant details

  - type: checkboxes
    id: kids_category_compliance
    attributes:
      label: Kids Category Compliance
      description: Confirm this report follows our guidelines
      options:
        - label: This report contains no personal information about children or families
          required: true
        - label: This report does not violate COPPA guidelines
          required: true 